autohotspot update

diff --git a/autohotspot/autohotspot b/autohotspot/autohotspot
--- a/autohotspot/autohotspot
+++ b/autohotspot/autohotspot
@@ -1,78 +1,156 @@
 #!/bin/bash
-#Script to switch between a wifi network and a No Internet Hotspot without rebooting
-#Other setup required find out more at 
-#http://www.raspberryconnect.com/network/item/315-raspberry-pi-3-auto-wifi-hotspot-if-no-internet
-# These two lines check if any of the wifi networks already setup are in range
-wpassid=$(awk '/ssid="/{ print $0 }' /etc/wpa_supplicant/wpa_supplicant.conf | awk -F'ssid=' '{ print $2 }' ORS=' ' | sed 's/\"/''/g' | sed 's/ $//')
+#version 0.95-1-N/HS-I
+
+#You may share this script on the condition a reference to RaspberryConnect.com 
+#must be included in copies or derivatives of this script. 
+
+#Network Wifi & Hotspot with Internet
+#A script to switch between a wifi network and an Internet routed Hotspot
+#A Raspberry Pi with a network port required for Internet in hotspot mode.
+#Works at startup or with a seperate timer or manually without a reboot
+#Other setup required find out more at
+#http://www.raspberryconnect.com
+
+wifidev="wlan0" #device name to use. Default is wlan0.
+#use the command: iw dev ,to see wifi interface name 
+
+IFSdef=$IFS
+cnt=0
+#These four lines capture the wifi networks the RPi is setup to use
+wpassid=$(awk '/ssid="/{ print $0 }' /etc/wpa_supplicant/wpa_supplicant.conf | awk -F'ssid=' '{ print $2 }' ORS=',' | sed 's/\"/''/g' | sed 's/,$//')
+IFS=","
 ssids=($wpassid)
-#Note:If you only want to check for certain SSids
-#Remove the # in in front of ssids=('mySSID1'....  and 
-#put a # infront of  ssids=$(awk '..... & ssids($wpassid) in the lines above
-# separated by a space, ('mySSID1' 'mySSID2')
+IFS=$IFSdef #reset back to defaults
+
+
+#Note:If you only want to check for certain SSIDs
+#Remove the # in in front of ssids=('mySSID1'.... below and put a # infront of all four lines above
+# separated by a space, eg ('mySSID1' 'mySSID2')
 #ssids=('mySSID1' 'mySSID2' 'mySSID3')
+
+#Enter the Routers Mac Addresses for hidden SSIDs, seperated by spaces ie 
+#( '11:22:33:44:55:66' 'aa:bb:cc:dd:ee:ff' ) 
+mac=()
+
+ssidsmac=("${ssids[@]}" "${mac[@]}") #combines ssid and MAC for checking
+
 createAdHocNetwork()
 {
-    ip link set dev wlan0 down
-    ip a add 10.0.44.1/24 dev wlan0
-    ip link set dev wlan0 up
+    ip link set dev "$wifidev" down
+    ip a add 10.0.44.1/24 brd + dev "$wifidev"
+    ip link set dev "$wifidev" up
+    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
+    iptables -A FORWARD -i eth0 -o "$wifidev" -m state --state RELATED,ESTABLISHED -j ACCEPT
+    iptables -A FORWARD -i "$wifidev" -o eth0 -j ACCEPT
     systemctl start dnsmasq
     systemctl start hostapd
+    echo 1 > /proc/sys/net/ipv4/ip_forward
 }
+
 KillHotspot()
 {
-	echo "Shutting Down Hotspot"
-	ip link set dev wlan0 down
-	systemctl stop hostapd
-	systemctl stop dnsmasq
-	ip addr flush dev wlan0
-	ip link set dev wlan0 up
+    echo "Shutting Down Hotspot"
+    ip link set dev "$wifidev" down
+    systemctl stop hostapd
+    systemctl stop dnsmasq
+    iptables -D FORWARD -i eth0 -o "$wifidev" -m state --state RELATED,ESTABLISHED -j ACCEPT
+    iptables -D FORWARD -i "$wifidev" -o eth0 -j ACCEPT
+    echo 0 > /proc/sys/net/ipv4/ip_forward
+    ip addr flush dev "$wifidev"
+    ip link set dev "$wifidev" up
 }
-#ssid in range check
+
+ChkWifiUp()
+{
+	echo "Checking WiFi connection ok"
+        sleep 10 #give time for connection to be completed to router
+	if ! wpa_cli -i "$wifidev" status | grep 'ip_address' >/dev/null 2>&1
+        then #Failed to connect to wifi (check your wifi settings, password etc)
+	       echo 'Wifi failed to connect, falling back to Hotspot.'
+               wpa_cli terminate "$wifidev" >/dev/null 2>&1
+	       createAdHocNetwork
+	fi
+}
+
+
+FindSSID()
+{
+#Check to see what SSID's and MAC addresses are in range
 ssidChk=('NoSSid')
-for ssid in "${ssids[@]}"
-do 
-	if iw dev wlan0 scan ap-force | grep "$ssid" > /dev/null ;then
-		ssidChk=$ssid
-                break
-	else
-		ssidChk='NoSSid'
+i=0; j=0
+until [ $i -eq 1 ] #wait for wifi if busy, usb wifi is slower.
+do
+        ssidreply=$((iw dev "$wifidev" scan ap-force | egrep "^BSS|SSID:") 2>&1) >/dev/null 2>&1 
+	if echo "$ssidreply" | grep "No such device (-19)" >/dev/null 2>&1; then
+		NoDevice
+	elif ! echo "$ssidreply" | grep "resource busy (-16)"  >/dev/null 2>&1 ;then
+		i=1
+	elif (($j >= 5)); then #if busy 5 times goto hotspot
+                 ssidreply=""
+		 i=1
+	else #see if device not busy in 2 seconds
+		j=$((j = 1))
+		sleep 2
 	fi
-done 
-if [ $ssidChk != "NoSSid" ] 
+done
+
+for ssid in "${ssidsmac[@]}"
+do
+     if (echo "$ssidreply" | grep "$ssid") >/dev/null 2>&1
+     then
+	      #Valid SSid found, passing to script
+              ssidChk=$ssid
+              return 0
+      else
+	      #No Network found, NoSSid issued"
+              ssidChk='NoSSid'
+     fi
+done
+}
+
+NoDevice()
+{
+	#if no wifi device,ie usb wifi removed, activate wifi so when it is
+	#reconnected wifi to a router will be available
+	echo "No wifi device connected"
+	wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
+	exit 1
+}
+
+FindSSID
+
+#Create Hotspot or connect to valid wifi networks
+if [ "$ssidChk" != "NoSSid" ] 
 then
-	if systemctl status hostapd | grep "(running)"
-	then #hotspot running and ssid in range
-		KillHotspot
-		echo "Hotspot Deactivated, Bringing Wifi Up"
-        	wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null 2>&1
-	elif wpa_cli status | grep 'wlan0'
-	then #If already connected stop script
-		echo "Wifi already connected to network"
-	else #ssid exists and no hotspot running connect to wifi network
-		echo "Connecting to WiFi Network"
-		wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf > /dev/null 2>&1
-        	if wpa_cli status | grep 'wlan0' > /dev/null
-        	then
-			echo "Wifi connection ok"
-        	else
-			echo "Wifi failed to connect, Creating Hotspot instead"
-            		wpa_cli terminate
-			createAdHocNetwork
-        	fi
-	fi
-else #ssid not in range
-    	if systemctl status hostapd | grep "(running)" > /dev/null 
-	then
-		echo "Hostspot already active"
-	elif wpa_cli status | grep 'wlan0' > /dev/null
-	then
-		echo "Cleaning wifi files and Activating Hotspot"
-		wpa_cli terminate
-		ip addr flush wlan0
-		ip link set dev wlan0 down
-		rm -r /var/run/wpa_supplicant > /dev/null
-		createAdHocNetwork
-	else #"No SSID, activating Hotspot"
-		createAdHocNetwork
-	fi
-fi
+       echo 0 > /proc/sys/net/ipv4/ip_forward #deactivate ip forwarding
+       if systemctl status hostapd | grep "(running)" >/dev/null 2>&1
+       then #hotspot running and ssid in range
+              KillHotspot
+              echo "Hotspot Deactivated, Bringing Wifi Up"
+              wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
+              ChkWifiUp
+       elif { wpa_cli -i "$wifidev" status | grep 'ip_address'; } >/dev/null 2>&1
+       then #Already connected
+              echo "Wifi already connected to a network"
+       else #ssid exists and no hotspot running connect to wifi network
+              echo "Connecting to the WiFi Network"
+              wpa_supplicant -B -i "$wifidev" -c /etc/wpa_supplicant/wpa_supplicant.conf >/dev/null 2>&1
+              ChkWifiUp
+       fi
+else #ssid or MAC address not in range
+       if systemctl status hostapd | grep "(running)" >/dev/null 2>&1
+       then
+              echo "Hostspot already active"
+       elif { wpa_cli status | grep "$wifidev"; } >/dev/null 2>&1
+       then
+              echo "Cleaning wifi files and Activating Hotspot"
+              wpa_cli terminate >/dev/null 2>&1
+              ip addr flush "$wifidev"
+              ip link set dev "$wifidev" down
+              rm -r /var/run/wpa_supplicant >/dev/null 2>&1
+              ip link set dev "$wifidev" up
+              createAdHocNetwork
+       else #"No SSID, activating Hotspot"
+              createAdHocNetwork
+       fi 
+fi 
